main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('about/', views.about, name='about'),

]

project1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

def home(request):
    return render(request, 'main/home.html')

def log_in(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("main:home")
        return render(request, "main/login.html", {'success':False})
    return render(request, "main/login.html", {'success':True})

def log_out(request):
    logout(request)
    return redirect("main:home")

def signup(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        user = User.objects.create_user(username, email, password)
        user.save()
        return render(request, "main/login.html", {'success':True})
    return render(request, "main/signup.html")

def about(request):
    return render(request, 'main/about.html')

main/templates/main/about.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>Tentang</title>
<style>
</style>
{% endblock meta %}

{% block content %}
{% include "navbar.html" %}

<section class="logo"><a href="{% url 'main:home' %}">DonaTree <i class="fas fa-leaf"></i></a></section>
<section class="story">
    <h1>Our Story</h1>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum ducimus minima libero. Ullam odit pariatur quo. Suscipit animi fugit dolore tenetur sint dignissimos aliquid dicta distinctio illo ducimus ut fuga qui voluptas veritatis, neque eius, accusamus odit totam ipsam? Quia nihil incidunt, repellendus dicta deserunt amet pariatur veritatis? Libero, laborum!</p>
</section>
<section class="team"></section>
<section class="faq"></section>
<section class="contactus"></section>

{% include "footer.html" %}
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>Beranda</title>
<style>
</style>
{% endblock meta %}

{% block content %}
{% include "navbar.html" %}
<!-- <div class="main-container">
  <div class="home-text">
    <p>WELCOME TO <b>DONATREE!</b> by WINTER</p>
    <a href="" class="button">LOGIN</a>
  </div>
          
  <div class="home-image">
    <img src="../../static/img/home.jpg" alt="">
  </div>
</div> -->
<section class="header">
  {% if user.is_authenticated %}
  <h1>Welcome, {{user.username}}</h1>
  <a href="{% url 'main:logout' %}" class="login-btn">LOGOUT</a>
  {% else %}
  <h1>Welcome to DonaTree!</h1>
  <a href="{% url 'main:login' %}" class="login-btn">LOGIN</a>
  {% endif %}
  <!-- <span>Don't Have an Account? <a href="">Sign Up</a> here</span> -->
</section>
<section class="about">
  <h1>Planting Trees.<br> Restoring Hope.</h1>
  <p>DONATREE hadir dari kekhawatiran kami akan semakin berkurangnya lahan perhutanan di indonesia yang menyebabkan berbagai masalah seperti hilangnya habitat bagi flora dan fauna, serta berkurangnya daerah resapan hujan yang akan menyebabkan banjir dan tanah longsor.</p>
  <a href="" class="donate-btn"><b>Donate Now</b><i class="fas fa-chevron-right"></i></a>
</section>
<section class="features">
  <h1>Explore Our Features</h1>
  <div class="card-container">
    <div class="card">
      <div class="card-image donasi"></div>
      <div class="card-text">
        <h4><b>Donasi</b></h4>
      </div>
    </div>
    <div class="card">
      <div class="card-image pantau"></div>
      <div class="card-text">
        <h4><b>Pantau</b></h4>
      </div>
    </div>
    <div class="card">
      <div class="card-image tulis"></div>
      <div class="card-text">
        <h4><b>Tulis Artikel</b></h4>
      </div>
    </div>
    <div class="card">
      <div class="card-image baca"></div>
      <div class="card-text">
        <h4><b>Baca Artikel</b></h4>
      </div>
    </div>
  </div>
</section>

{% include "footer.html" %}
{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
{% include "navbar.html" %}
<section class="header">
  <form action="{% url 'main:login' %}" method="POST">
    {% csrf_token %}
    <div class="login-box">
      <h1>Log in</h1>
      <div class="login-input">
        <i class="fas fa-user"></i><input type="text" placeholder="Username" name="username">
      </div>        
      <div class="login-input">
        <i class="fas fa-lock"></i><input type="password" placeholder="Password" name="password">
      </div>
      <button class="login-btn" type="submit">Log In</button>
      {% if success == False %}
      <p style="color: red;">The username or password you entered is incorrect, please try again</p>
      {% endif %}
      <p></p>
    </div>
  </form>
  <p>Don't have an account? <a href="{% url 'main:signup' %}">Sign Up</a></p>
</section>
      
{% endblock content %}

main/templates/main/signup.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>Signup</title>
{% endblock meta %}

{% block content %}
{% include "navbar.html" %}
<section class="header">
  <form action="{% url 'main:signup' %}" method="POST">
    {% csrf_token %}
    <div class="login-box">
      <h1>Sign up</h1>
      <div class="login-input">
        <i class="fas fa-user"></i><input type="text" placeholder="Username" name="username">
      </div>        
      <div class="login-input">
        <i class="fas fa-at"></i><input type="email" placeholder="Email" name="email">
      </div>        
      <div class="login-input">
        <i class="fas fa-lock"></i><input type="password" placeholder="Password" name="password">
      </div>
      <button class="login-btn" type="submit">Sign Up</button>
      <!-- {% if success == False %}
      <p style="color: red;">The username or password you entered is , please try again</p>
      {% endif %}
      <p></p> -->
    </div>
  </form>
  <p>Already have an account? <a href="{% url 'main:login' %}">Log In</a></p>
</section>
      
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->

  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

templates/footer.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
{% endblock meta %}
{% block content %}
  <footer>
    <div class="logo"><a href="{% url 'main:home' %}">DonaTree</a></div>
    <div class="about">
      <p>Website ini adalah demo dari projek mata kuliah Sistem Interaksi Fasilkom UI 2019 yang bernama "DonaTree". DonaTree dirancang oleh kelompok "Winter", dan website demo ini dibuat oleh salah satu anggotanya, Aziz sebagai sarana latihan pribadi dalam mengembangkan skill front-end. </p>
    </div>
    <div class="contact">
      <h4>Contact Me</h4>
      <ul>
        <li><a href="https://www.instagram.com/aziz_js/"><i class="fab fa-instagram"></i></a></li>
        <li><a href="https://twitter.com/azizjabbar_s"><i class="fab fa-twitter"></i></a></li>
        <li><a href="https://web.facebook.com/aziz.jabbarshiddiq"><i class="fab fa-facebook"></i></a></li>
        <li><a href="https://www.linkedin.com/in/aziz-jabbar-178360194/"><i class="fab fa-linkedin"></i></a></li>
      </ul>
    </div>
  </footer>
{% endblock content %}

templates/navbar.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
{% endblock meta %}
{% block content %}
  <nav>
    <div class="logo"><a href="{% url 'main:home' %}">DonaTree <i class="fas fa-leaf"></i></a></div>
    
    <ul id="menu" class="menu">
      <li><a href="">DONASI</a></li>
      <li><a href="">PANTAU</a></li>
      <li><a href="">ARTIKEL</a></li>
      <li><a href="{% url 'main:about' %}">TENTANG</a></li>
      {% if user.is_authenticated %}
      <li class="hidden"><a href="">LOGOUT</a></li>
      {% endif %}
    </ul>
    
    <div class="auth">
      {% if user.is_authenticated %}
      <a href="{% url 'main:logout' %}"><i class="fas fa-user-circle" style="font-size: 1.5em;"></i></a>
      <div class="dropdown"><a href="{% url 'main:logout' %}">Logout</a></div>
      {% else %}
      <a href="{% url 'main:login' %}">LOGIN</a>
      {% endif %}
    </div>
    <div id="hamburger" onclick="myFunction()" class="hamburger">
      <div class="line 1"></div>
      <div class="line 2"></div>
      <div class="line 3"></div>
    </div>
  </nav>
  <script>
    function myFunction(){
      var x = document.getElementById("hamburger");
      if(x.className == "hamburger"){
        document.getElementById("menu").style.transform = "translateY(100vh)";
        x.className += " clicked";
      }
      else{
        document.getElementById("menu").style.transform = "translateY(-100vh)";
        x.className = "hamburger";
      }
    }
  </script>
{% endblock content %}